apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttsl-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: ttsl-frontend
  template:
    metadata:
      labels:
        app: ttsl-frontend
    spec:
      containers:
      - name: frontend-ui
        image: {{ .Values.frontend.image }}
        env:
        - name: BACKEND_URL
          value: "http://ttsl-backend-svc:5000"
        ports:
        - containerPort: {{ .Values.frontend.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: ttsl-frontend-svc
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 32000
  selector:
    app: ttsl-frontend
